spring:
  application:
    name: gulimall-auth-server

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848

#  redis:
#    host: 101.34.55.204
#    password: 547061946
#    timeout: 60000


server:
  port: 20000

ribbon:
  #\u6307\u7684\u662F\u5EFA\u7ACB\u8FDE\u63A5\u6240\u7528\u7684\u65F6\u95F4\uFF0C\u9002\u7528\u4E8E\u7F51\u7EDC\u72B6\u51B5\u6B63\u5E38\u7684\u60C5\u51B5\u4E0B,\u4E24\u7AEF\u8FDE\u63A5\u6240\u7528\u7684\u65F6\u95F4
  ReadTimeout: 60000
  #\u6307\u7684\u662F\u5EFA\u7ACB\u8FDE\u63A5\u540E\u4ECE\u670D\u52A1\u5668\u8BFB\u53D6\u5230\u53EF\u7528\u8D44\u6E90\u6240\u7528\u7684\u65F6\u95F4
  ConnectTimeout: 60000

